### ISSUE TITLE
Bug: Incorrect definition of R2m

### ISSUE THREAD

**Issue by MarcAchterstraat** [tsyet12/ProcessPLS#7]
R2m is computed using element-wise multiplication of matrices simpls.x_loadings_.T and simpls.x_loadings_.T, instead of the matrix multiplication of simpls.x_loadings_.T and simpls.x_loadings_. 

https://github.com/tsyet12/ProcessPLS/blob/0c1540f0716c60ac3ceaf7a0cdb6a2b92495b148/processPLS/model.py#L396

Hence, 
`simpls.x_loadings_.T*simpls.x_loadings_.T` should be replaced with
`np.dot(simpls.x_loadings_.T, simpls.x_loadings_)`

as the mulplication operator * in Python defaults to element-wise multiplication, contrary to Matlab.

**Comment by tsyet12** [comment]
Dear MarcAchterstraat,

Thank you for identifying this bug. It has been fixed. The official pypi library is also updated. 

Regards,
Sin Yong
